# Generated by Django 3.1.2 on 2020-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='bleeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='heartrate',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
