# Generated by Django 3.1.2 on 2020-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20201012_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiration_rate', models.IntegerField(default=20)),
                ('heart_rate', models.IntegerField(default=70)),
                ('next_state_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bleeding',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='heartrate',
        ),
        migrations.AddField(
            model_name='patient',
            name='current_state_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='hair_color',
            field=models.CharField(default='Orange', max_length=20),
        ),
    ]
