# Generated by Django 3.1.2 on 2020-10-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20201013_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstate',
            name='test_string',
            field=models.CharField(default='Hello World', max_length=100),
        ),
    ]
